apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ppk.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ppk.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  selector:
    matchLabels:
      {{- include "ppk.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "agent") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ppk.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "agent") | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ include "ppk.fullname" . }}-agent
      tolerations:
        - operator: "Exists"
      containers:
        - name: agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: COLLECTOR_URL
              value: "http://{{ include "ppk.fullname" . }}-collector.{{ .Release.Namespace }}.svc.cluster.local:8080/matrix"
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
