apiVersion: v1
kind: Service
metadata:
  name: {{ include "ppk.fullname" . }}-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ppk.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  type: ClusterIP
  selector:
    {{- include "ppk.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "collector") | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
