{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- $fullname := "" -}}
{{- if .Values.fullnameOverride -}}
{{- $fullname = .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else if contains $name .Release.Name -}}
{{- $fullname = .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $fullname = printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-collector
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: collector
    spec:
      containers:
        - name: collector
          image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: REPO_API_URL
              value: {{ .Values.repoApiUrl | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName | quote }}
            - name: K8S_MATRIX_PATH
              value: {{ printf "k8s/%s.yaml" .Values.clusterName | quote }}
            - name: K8S_DEFAULT_MATRIX_PATH
              value: "k8s/default.yaml"
            - name: NOTIFICATION_PATH
              value: "notification/discord.yaml"
            - name: MATRIX_ENDPOINT
              value: "/matrix"
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullname }}-auth
                  key: git-token
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
