{{- if .Values.matrixConfigMap.create -}}
{{- $name := default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pingpongkong-{{ .Values.K8S_CLUSTERNAME }}-ping-state
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: matrix
data:
  {{ .Values.matrixConfigMap.key | quote }}: |
{{ .Values.matrixConfigMap.data | trim | indent 4 }}
{{- end }}
