{{- if .Values.auth.gitToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  git-token: {{ .Values.auth.gitToken | quote }}
{{- end }}